qlib_init:
  provider_uri:
    day: "~/.qlib/qlib_data/forex_data_day"
    1min: "~/.qlib/qlib_data/forex_data_1min"
  region: us
  dataset_cache: null
  maxtasksperchild: 1
market: &market forex
benchmark: &benchmark EURUSD
data_handler_config: &data_handler_config
  start_time: 2022-01-01
  # 1min closing time is 15:00:00
  end_time: "2024-11-01 15:00:00"
  fit_start_time: 2008-01-01
  fit_end_time: 2014-12-31
  instruments: *market
  freq:
    label: day
    feature: 1min
  # with label as reference
  inst_processors:
    feature:
      - class: Resample1minProcessor
        module_path: features_sample.py
        kwargs:
          hour: 14
          minute: 56

port_analysis_config: &port_analysis_config
  strategy:
    class: TopkDropoutStrategy
    module_path: qlib.contrib.strategy.signal_strategy
    kwargs:
      topk: 50
      n_drop: 5
      signal: <PRED>
  backtest:
    account: 100000000
    benchmark: *benchmark

    start_time: 2022-01-01
    end_time: "2024-11-01 15:00:00"
task:
  model:
    class: LGBModel
    module_path: qlib.contrib.model.gbdt
    kwargs:
      loss: mse
      colsample_bytree: 0.8879
      learning_rate: 0.2
      subsample: 0.8789
      lambda_l1: 205.6999
      lambda_l2: 580.9768
      max_depth: 8
      num_leaves: 210
      num_threads: 20
  dataset:
    class: DatasetH
    module_path: qlib.data.dataset
    kwargs:
      handler:
        class: Alpha158
        module_path: qlib.contrib.data.handler
        kwargs: *data_handler_config
      segments:
        train: [2022-01-01, 2022-12-31]
        valid: [2023-01-01, 2023-12-31]
        test: [2024-01-01, 2024-11-01]
  record:
    - class: SignalRecord
      module_path: qlib.workflow.record_temp
      kwargs: {}
    - class: SigAnaRecord
      module_path: qlib.workflow.record_temp
      kwargs:
        ana_long_short: False
        ann_scaler: 252
    - class: PortAnaRecord
      module_path: qlib.workflow.record_temp
      kwargs:
        config: *port_analysis_config
